# Generated by Django 4.2.8 on 2025-08-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('day', 'Day Cruise'), ('night', 'Night Cruise'), ('festival', 'Festival Day Cruise')], default='day', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('riel', 'Riel')], default='usd', max_length=4)),
                ('seats_required', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
            ],
        ),
    ]
