# Generated by Django 4.2.8 on 2025-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mekong_cruises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='time',
        ),
        migrations.AddField(
            model_name='journey',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Quick Transfer')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='journey',
            name='requests',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='journey',
            name='time_slots',
            field=models.CharField(choices=[('09.00', '09:00AM'), ('10.00', '10:00AM'), ('11.00', '11:00AM'), ('12.00', '12:00PM'), ('13.00', '13:00PM'), ('14.00', '14:00PM'), ('15.00', '15:00PM'), ('16.00', '16:00PM'), ('17.00', '17:00PM'), ('18.00', '18:00PM'), ('19.00', '19:00PM'), ('20.00', '20:00PM'), ('21.00', '21:00PM'), ('22.00', '22:00PM')], default='09.00', max_length=5),
        ),
        migrations.AlterField(
            model_name='journey',
            name='price',
            field=models.CharField(choices=[('15.00', '$15.00 Standard Day (approx. 62,000 Riel)'), ('20.00', '$20.00 Standard Night (approx. 80,000 Riel)'), ('25.00', '$25.00 Festival Day (approx. 100,000 Riel)'), ('30.00', '$30.00 Festival Night (approx. 120,000 Riel)')], default='15.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='journey',
            name='type',
            field=models.CharField(choices=[('day', 'Day Cruise 09.00AM - 16.00PM'), ('night', 'Night Cruise 17.00PM - 22.00PM'), ('festival', 'Day Festival Cruise 09.00AM - 16.00PM'), ('night_festival', 'Night Festival Cruise 17.00PM - 22.00PM')], default='day', max_length=20),
        ),
    ]
